### PR TITLE
Add tests to CI (and marking currently broken ones)

### PR DESCRIPTION
**Pull request by mm-zk**
# What ❔

* enabling tests in CI
* marking currently broken tests with 'ignore' - to make CI green.

## Why ❔

* Running tests in CI will improve code security.

### CODE REVIEW

**Review by shamatar — CHANGES_REQUESTED** [review]
What's a purpose if everything material is too slow or ignored?

**Comment by mm-zk** [comment]
@shamatar - there are still couple that are passing (and now they will be covered in the CI).

And for the broken ones - I'm fixing them right now (fixes will be coming in upcoming PRs).

**Comment by shamatar** [comment]
I would rather run a part of basic_test in satisfiability testing mode (and until recursion of course) and only it, instead of those passing ones

**Review by EmilLuta — APPROVED** [review]

**Comment by EmilLuta** [comment]
Basic test could be split in multiple parts in the future and you could run them 1 by 1 in CI. That'd get us the best coverage, together with CI. I'm happy with above changes.

**Pull request merged**
